---
- name: install cgit packages
  yum : name={{ item }} state=installed
  with_items:
  - cgit
  - highlight
  - policycoreutils-python
  - policycoreutils-restorecond

- name: enable traversal
  file: path={{ cgit_root }} mode=755

- name: enable project list access so apache can access it
  file: path={{ cgit_project_list }} mode=644

- name: set correct selinux contexts
  shell: semanage fcontext -a -t httpd_sys_content_t "{{ cgit_project_list }}"
  when: common_selinux

- name: set correct selinux contexts
  shell: semanage fcontext -a -t httpd_sys_content_t "{{ cgit_scan_path }}(/.*)?"
  when: common_selinux

- name: enable git_cgi_enable_homedirs selinux boolean
  seboolean: name=git_cgi_enable_homedirs state=yes persistent=yes
  when: common_selinux

- name: restorecon for git dir
  shell: restorecon -v -F -R /srv/git
  when: common_selinux

- name: add git dirs to restorecond
  lineinfile: "dest=/etc/selinux/restorecond.conf
    line='{{ item.line }}'
    regexp='{{ item.regexp }}'"
  with_items:
    - { line: '{{ cgit_project_list }}',
        regexp: '^{{ cgit_project_list }}$' }
    - { line: '{{ cgit_scan_path }}',
        regexp: '^{{ cgit_scan_path }}$' }
    - { line: '{{ cgit_scan_path }}/*',
        regexp: '^{{ cgit_scan_path }}/\*$' }
  when: common_selinux

- name: enable restorecond
  service: name=restorecond enabled=yes state=running
  when: common_selinux

- name: install cgit config
  template:
    src=etc-cgitrc.j2
    dest=/etc/cgitrc

- name: install httpd config for cgit
  template:
    src=httpd_cgit.conf.j2
    dest=/etc/httpd/conf.d/cgit.conf
  notify:
    - restart apache
