- name: install packages
  yum : name={{ item }} state=installed
  with_items:
    - openssl
    - "{{ common_install_packages }}"

- name: uninstall packages
  yum : name={{ item }} state=removed
  with_items:
    - "{{ common_remove_packages }}"

- name: disable dnf-makecache
  service: name=dnf-makecache enabled=no
  when: ansible_distribution == 'Fedora'

- name: disable dnf-makecache.timer
  service: name=dnf-makecache.timer enabled=no
  when: ansible_distribution == 'Fedora'
