---
###############################################################################
# Set your variables here.
# For a complete reference look at the `vars/defaults.yml` file.
###############################################################################

# common
domain: TODO.com
main_user_name: TODO
encfs_password: TODO

# database
db_admin_username: postgres
db_admin_password: TODO

# ircbouncer
irc_nick: TODO
irc_ident: TODO
irc_realname: TODO
irc_quitmsg: TODO
irc_password_hash: TODO
irc_password_salt: TODO
irc_timezone: TODO      #Example: "America/New_York"

# mailserver
mail_db_password: TODO
mail_virtual_domains:
  - name: "{{ domain }}"
    pk_id: 1
#  - name: TODO.com
#    pk_id: 2
mail_virtual_users:
  - account: "{{ main_user_name }}"
    domain: "{{ domain }}"
    password_hash: TODO
    domain_pk_id: 1
#  - account: "{{ TODO }}"
#    domain: "{{ domain }}"
#    password_hash: TODO
#    domain_pk_id: 2
mail_virtual_aliases:
  - source: "root@{{ domain }}"
    destination: "{{ admin_email }}"
    domain_pk_id: 1
  - source: "postmaster@{{ domain }}"
    destination: "{{ admin_email }}"
    domain_pk_id: 1
  - source: "webmaster@{{ domain }}"
    destination: "{{ admin_email }}"
    domain_pk_id: 1
mail_header_privacy: 1

# z-push
zpush_timezone: "TODO"  #Example: "America/New_York"

# owncloud
owncloud_db_password: TODO

# vpn
openvpn_key_country:  "US"
openvpn_key_province: "California"
openvpn_key_city: "Beverly Hills"
openvpn_key_org: "ACME CORPORATION"
openvpn_key_ou: "Anvil Department"
openvpn_clients:
  - laptop
  - phone
  - tablet

# webmail
webmail_db_password: TODO

# xmpp
prosody_admin: "{{ admin_email }}"
prosody_virtual_domain: "{{ domain }}"
prosody_accounts:
  - name: "{{ main_user_name }}"
    password: TODO

# selfoss
selfoss_db_password: "TODO"
selfoss_username: "{{ main_user_name }}"
# this is the sha512 hash of the desired password
selfoss_password_hash: "TODO"

# wallabag
wallabag_salt: TODO
wallabag_db_password: TODO
