---
- hosts: loadbalancer
  become: yes
  become_method: sudo
  remote_user: root
  roles:
     - loadbalancer

- hosts: webservers
  become: yes
  become_method: sudo
  remote_user: root
  roles:
     - tomcat

- hosts: database
  become: yes
  become_method: sudo
  remote_user: root
  roles:
     - mysql
