---
galaxy_info:
  author: Richard Marko <rmarko@base48.cz>
  description: Common system setup
  license: BSD
  min_ansible_version: 1.9
  platforms:
   - name: EL
     versions:
      - 7
   - name: Fedora
     versions:
      - 21
      - 22
      - 23
  categories:
   - system
