---
# tasks file for icinga2-ansible-classic-ui

- include_tasks: icinga2_classic_ui_Debian_install.yml
  when: ansible_os_family == 'Debian'

- include_tasks: icinga2_classic_ui_RedHat_install.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: icinga2_classic_ui_Gentoo_install.yml
  when: ansible_os_family == 'Gentoo'
