---

- stat: path=/usr/bin/journalctl
  register: journalctl

- name: install template
  template: src=journald.conf.j2 dest=/etc/systemd/journald.conf
  notify:
    - restart journald
  when: journalctl.stat.exists

- name: remove /var/log/journald
  file: path=/var/log/journal/ state=absent
  when: journald_remove_storage
