---

- name: install template
  template:
    src=cpupower.j2
    dest=/etc/sysconfig/cpupower
    owner=root group=root mode=0640
  notify:
    - restart cpupower

- name: restart if required
  meta: flush_handlers

- name: start and enable service
  service: name=cpupower state=started enabled=yes
