---
# tasks file for loadbalancer

- name: configure nginx rpm
  yum: name=http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
- name: Install ngixn server
  yum:
    name: nginx
    state: present
    enablerepo: nginx
- name: start and enable nginx server
  service:
     name: nginx
     state: started
     enabled: yes
- name: copy nginx.conf to the nginx server
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: restart the server
