
 CREATE TABLE STUDENTS_DEVOPS (
     id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
     firstname VARCHAR(30) NOT NULL,
     lastname VARCHAR(30) NOT NULL
 );

INSERT INTO STUDENTS_DEVOPS(firstname,lastname) VALUES('Hari','Kammana');
INSERT INTO STUDENTS_DEVOPS(firstname,lastname) VALUES('Raghu','Ram');
