---

- name: Remove welcome.conf
  file: path=/etc/httpd/conf.d/welcome.conf state=absent
  when: apache_no_welcome_conf

- name: Remove userdir.conf
  file: path=/etc/httpd/conf.d/userdir.conf state=absent
  when: apache_no_userdir_conf
