---
- name: install rmarko-sniproxy COPR repo file
  copy:
    src=rmarko-sniproxy.repo
    dest=/etc/yum.repos.d/rmarko-sniproxy-epel-7.repo
  when: ansible_os_family == 'RedHat' and ansible_distribution != 'Fedora'

- name: install packages
  yum: name={{ item }} state=present
  with_items:
    - sniproxy

- name: install template
  template:
    src=etc_sniproxy.conf.j2
    dest=/etc/sniproxy.conf
    owner=root group=root mode=0640
  notify:
    - restart sniproxy

- name: start and enable service
  service: name=sniproxy state=started enabled=yes
